version: '3'

services:
  postgres:
    image: postgres
    environment:
      POSTGRES_DB: users
      POSTGRES_PASSWORD: example1234
      POSTGRES_USER: admin
    ports:
      - 5432:5432
    volumes:
      - ./resources/db/migrations/v0001_init.sql:/docker-entrypoint-initdb.d/v0001_init.sql
