version: 2.1
orbs:
  node: circleci/node@3.0.0
jobs:

  build:
    machine:
      enabled: true
    steps:
      - checkout
      - run: docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
      - run: docker-compose build --force-rm users-api
      - run: docker build -t murilokakazu/tempao-users-api:$CIRCLE_SHA1 ./
      - run: docker push murilokakazu/tempao-users-api:$CIRCLE_SHA1
      - run: git tag V_$CIRCLE_BUILD_NUM
      - run: git push --tags

  deploy:
    machine:
      enabled: true
    steps:
      - checkout
      - run: |
          sudo apt-get update && \
          sudo apt-get install -y awscli
      - run: |
          chmod +x ./.deploy/bin/setup.sh && \
          ./.deploy/bin/setup.sh

workflows:
  build-deploy:
    jobs:
      - build:
          context: docker-context
          filters:
            branches:
              only: master

      - hold_deploy:
          type: approval
          requires:
            - build
          filters:
            branches:
              only: master

      - deploy:
          context: deployment-context
          requires:
            - hold_deploy
          filters:
            branches:
              only: master
