version: 2.1
orbs:
  node: circleci/node@3.0.0
jobs:

  build_push_image:
    machine:
      enabled: true
    steps:
      - checkout
      - run: docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
      - run: docker-compose build --force-rm users-api
      - run: docker build -t murilokakazu/tempao-users-api:$CIRCLE_SHA1 ./
      - run: docker push murilokakazu/tempao-users-api:$CIRCLE_SHA1
      - run: git tag V_$CIRCLE_BUILD_NUM
      - run: git push --tags

  deploy:
    machine:
      enabled: true
    steps:
      - checkout
      - run: |
         sudo apt-get update
         sudo apt-get install -y awscli
      - run: |
        zip -r deployment-${CIRCLE_SHA1}.zip ./
        aws s3 cp deployment-${CIRCLE_SHA1}.zip s3://elasticbeanstalk-sa-east-1-025606474706
        aws elasticbeanstalk create-application-version --application-name tempao-users-api \
            --version-label ${CIRCLE_SHA1} --source-bundle S3Bucket="elasticbeanstalk-sa-east-1-025606474706",S3Key="deployment-${CIRCLE_SHA1}.zip"
        aws elasticbeanstalk update-environment --application-name tempao-users-api \
            --environment-name staging1 --version-label ${CIRCLE_SHA1}

workflows:
  build-deploy:
    jobs:

      - build_push_image:
        context: docker-context
        filters:
          branches:
            only: master

      - hold_deploy:
        type: approval
        requires:
          - build_push_image
        filters:
          branches:
            only: master

      - build_push_image:
        context: aws-context
        requires:
          - hold_deploy
        filters:
          branches:
            only: master
